version: "3"
services:
  postgres:
    image: library/postgres:12.3
#    volumes:
#      - ./postgres/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bmat
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    networks:
      - tools

  app:
    build: django_project/
    command: /bin/sh start.sh
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=123321
    volumes:
      - ./data:/django_project/data
    networks:
      - tools
networks:
    tools: