version: "3"
services:
  postgres:
    image: library/postgres:12.3
#    volumes:
#      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgres/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bmat
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
